#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 26 10:40:01 2020

@author: ghiggi
"""

# Weight initialization seed
from numpy.random import seed
seed(1)
from tensorflow import set_random_seed
set_random_seed(2)
 
initializer = tf.keras.initializers.RandomNormal(mean=0., stddev=1., seed=1)
initializer = tf.keras.initializers.GlorotNormal(seed=1)
initializer = tf.keras.initializers.VarianceScaling(scale=0.1, 
                                                    mode='fan_in',
                                                    distribution='uniform',
                                                    seed=1)
layer = tf.keras.layers.Dense(3, kernel_initializer=initializer)